name: Deploy

on:
  push:
    branches: [dev]

jobs:
  runs-on: ubuntu-latest

  steps:
    
    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}